################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/jdk/windows/transport/socket \
src/jdk/windows/transport/shmem \
src/jdk/windows/npt \
src/jdk/windows/native/sun/windows \
src/jdk/windows/native/sun/tracing/dtrace \
src/jdk/windows/native/sun/tools/attach \
src/jdk/windows/native/sun/security/smartcardio \
src/jdk/windows/native/sun/security/provider \
src/jdk/windows/native/sun/security/pkcs11/wrapper \
src/jdk/windows/native/sun/security/pkcs11 \
src/jdk/windows/native/sun/security/mscapi \
src/jdk/windows/native/sun/security/krb5 \
src/jdk/windows/native/sun/nio/fs \
src/jdk/windows/native/sun/nio/ch \
src/jdk/windows/native/sun/net/www/protocol/http/ntlm \
src/jdk/windows/native/sun/net/spi \
src/jdk/windows/native/sun/net/dns \
src/jdk/windows/native/sun/management \
src/jdk/windows/native/sun/java2d/windows \
src/jdk/windows/native/sun/java2d/opengl \
src/jdk/windows/native/sun/java2d/d3d \
src/jdk/windows/native/sun/io \
src/jdk/windows/native/sun/font \
src/jdk/windows/native/sun/awt_common \
src/jdk/windows/native/sun/awt/splashscreen \
src/jdk/windows/native/java/util \
src/jdk/windows/native/java/nio \
src/jdk/windows/native/java/net \
src/jdk/windows/native/java/lang \
src/jdk/windows/native/java/io \
src/jdk/windows/native/common \
src/jdk/windows/native/com/sun/security/auth/module \
src/jdk/windows/native/com/sun/media/sound \
src/jdk/windows/native/com/sun/management \
src/jdk/windows/instrument \
src/jdk/windows/demo/jvmti/hprof \
src/jdk/windows/bin \
src/jdk/windows/back \
src/jdk/solaris/transport/socket \
src/jdk/solaris/npt \
src/jdk/solaris/native/sun/xawt \
src/jdk/solaris/native/sun/tracing/dtrace \
src/jdk/solaris/native/sun/tools/attach \
src/jdk/solaris/native/sun/security/smartcardio \
src/jdk/solaris/native/sun/security/pkcs11/wrapper \
src/jdk/solaris/native/sun/security/pkcs11 \
src/jdk/solaris/native/sun/security/jgss/wrapper \
src/jdk/solaris/native/sun/nio/fs \
src/jdk/solaris/native/sun/nio/ch \
src/jdk/solaris/native/sun/net/spi \
src/jdk/solaris/native/sun/net/sdp \
src/jdk/solaris/native/sun/net/dns \
src/jdk/solaris/native/sun/management \
src/jdk/solaris/native/sun/jdga \
src/jdk/solaris/native/sun/java2d/x11 \
src/jdk/solaris/native/sun/java2d/opengl \
src/jdk/solaris/native/sun/java2d/loops \
src/jdk/solaris/native/sun/font \
src/jdk/solaris/native/sun/awt \
src/jdk/solaris/native/sun/awt/splashscreen \
src/jdk/solaris/native/sun/awt/medialib \
src/jdk/solaris/native/java/util \
src/jdk/solaris/native/java/nio \
src/jdk/solaris/native/java/net \
src/jdk/solaris/native/java/lang \
src/jdk/solaris/native/java/io \
src/jdk/solaris/native/common \
src/jdk/solaris/native/com/sun/security/auth/module \
src/jdk/solaris/native/com/sun/media/sound \
src/jdk/solaris/native/com/sun/management \
src/jdk/solaris/instrument \
src/jdk/solaris/demo/jvmti/hprof \
src/jdk/solaris/demo/jni/Poller \
src/jdk/solaris/bin \
src/jdk/solaris/back \
src/jdk/share/transport/socket \
src/jdk/share/transport/shmem \
src/jdk/share/sample/vm/jvm-clr \
src/jdk/share/sample/vm/clr-jvm \
src/jdk/share/npt \
src/jdk/share/native/sun/tracing/dtrace \
src/jdk/share/native/sun/security/smartcardio \
src/jdk/share/native/sun/security/pkcs11/wrapper \
src/jdk/share/native/sun/security/pkcs11 \
src/jdk/share/native/sun/security/krb5 \
src/jdk/share/native/sun/security/jgss/wrapper \
src/jdk/share/native/sun/security/ec/impl \
src/jdk/share/native/sun/security/ec \
src/jdk/share/native/sun/rmi/server \
src/jdk/share/native/sun/reflect \
src/jdk/share/native/sun/nio/ch \
src/jdk/share/native/sun/misc \
src/jdk/share/native/sun/management \
src/jdk/share/native/sun/java2d/pipe \
src/jdk/share/native/sun/java2d/opengl \
src/jdk/share/native/sun/java2d/loops \
src/jdk/share/native/sun/java2d/cmm/lcms \
src/jdk/share/native/sun/java2d \
src/jdk/share/native/sun/font \
src/jdk/share/native/sun/font/layout \
src/jdk/share/native/sun/awt/utility \
src/jdk/share/native/sun/awt/splashscreen \
src/jdk/share/native/sun/awt/medialib \
src/jdk/share/native/sun/awt/libpng \
src/jdk/share/native/sun/awt/image/jpeg \
src/jdk/share/native/sun/awt/image \
src/jdk/share/native/sun/awt/image/gif \
src/jdk/share/native/sun/awt/image/cvutils \
src/jdk/share/native/sun/awt/giflib \
src/jdk/share/native/sun/awt/debug \
src/jdk/share/native/java/util/zip/zlib-1.2.3 \
src/jdk/share/native/java/util/zip \
src/jdk/share/native/java/util/concurrent/atomic \
src/jdk/share/native/java/util \
src/jdk/share/native/java/sql \
src/jdk/share/native/java/security \
src/jdk/share/native/java/nio \
src/jdk/share/native/java/net \
src/jdk/share/native/java/lang/reflect \
src/jdk/share/native/java/lang/ref \
src/jdk/share/native/java/lang/fdlibm/src \
src/jdk/share/native/java/lang \
src/jdk/share/native/java/io \
src/jdk/share/native/common \
src/jdk/share/native/com/sun/tools/jdi \
src/jdk/share/native/com/sun/media/sound \
src/jdk/share/native/com/sun/java/util/jar/pack \
src/jdk/share/instrument \
src/jdk/share/demo/jvmti/waiters \
src/jdk/share/demo/jvmti/versionCheck \
src/jdk/share/demo/jvmti/mtrace \
src/jdk/share/demo/jvmti/minst \
src/jdk/share/demo/jvmti/java_crw_demo \
src/jdk/share/demo/jvmti/hprof \
src/jdk/share/demo/jvmti/heapViewer \
src/jdk/share/demo/jvmti/heapTracker \
src/jdk/share/demo/jvmti/gctest \
src/jdk/share/demo/jvmti/compiledMethodLoad \
src/jdk/share/demo/jvmti/agent_util \
src/jdk/share/demo/applets/WireFrame/models \
src/jdk/share/bin \
src/jdk/share/back \
src/jdk/macosx/native/sun/nio/ch \
src/jdk/macosx/native/com/sun/media/sound \
src/jdk/macosx/bin \
src/hotspot/share/vm/utilities \
src/hotspot/share/vm/shark \
src/hotspot/share/vm/services \
src/hotspot/share/vm/runtime \
src/hotspot/share/vm/prims \
src/hotspot/share/vm/opto \
src/hotspot/share/vm/oops \
src/hotspot/share/vm/memory \
src/hotspot/share/vm/libadt \
src/hotspot/share/vm/interpreter \
src/hotspot/share/vm/gc_interface \
src/hotspot/share/vm/gc_implementation/shared \
src/hotspot/share/vm/gc_implementation/parallelScavenge \
src/hotspot/share/vm/gc_implementation/parNew \
src/hotspot/share/vm/gc_implementation/g1 \
src/hotspot/share/vm/gc_implementation/concurrentMarkSweep \
src/hotspot/share/vm/compiler \
src/hotspot/share/vm/code \
src/hotspot/share/vm/classfile \
src/hotspot/share/vm/ci \
src/hotspot/share/vm/c1 \
src/hotspot/share/vm/asm \
src/hotspot/share/vm/adlc \
src/hotspot/share/tools/launcher \
src/hotspot/share/tools/hsdis \
src/hotspot/os_cpu/windows_x86/vm \
src/hotspot/os_cpu/solaris_x86/vm \
src/hotspot/os_cpu/solaris_sparc/vm \
src/hotspot/os_cpu/linux_zero/vm \
src/hotspot/os_cpu/linux_x86/vm \
src/hotspot/os_cpu/linux_sparc/vm \
src/hotspot/os_cpu/bsd_zero/vm \
src/hotspot/os_cpu/bsd_x86/vm \
src/hotspot/os/windows/vm \
src/hotspot/os/windows/launcher \
src/hotspot/os/solaris/vm \
src/hotspot/os/solaris/fix_empty_sec_hdr_flags \
src/hotspot/os/solaris/dtrace \
src/hotspot/os/solaris/add_gnu_debuglink \
src/hotspot/os/posix/vm \
src/hotspot/os/posix/launcher \
src/hotspot/os/linux/vm \
src/hotspot/os/bsd/vm \
src/hotspot/os/bsd/dtrace \
src/hotspot/cpu/zero/vm \
src/hotspot/cpu/x86/vm \
src/hotspot/cpu/sparc/vm \

