################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/jdk/windows/native/sun/windows/CmdIDList.cpp \
../src/jdk/windows/native/sun/windows/ComCtl32Util.cpp \
../src/jdk/windows/native/sun/windows/Devices.cpp \
../src/jdk/windows/native/sun/windows/DllUtil.cpp \
../src/jdk/windows/native/sun/windows/GDIHashtable.cpp \
../src/jdk/windows/native/sun/windows/Hashtable.cpp \
../src/jdk/windows/native/sun/windows/MouseInfo.cpp \
../src/jdk/windows/native/sun/windows/ObjectList.cpp \
../src/jdk/windows/native/sun/windows/ShellFolder2.cpp \
../src/jdk/windows/native/sun/windows/ThemeReader.cpp \
../src/jdk/windows/native/sun/windows/WBufferStrategy.cpp \
../src/jdk/windows/native/sun/windows/WPrinterJob.cpp \
../src/jdk/windows/native/sun/windows/awt_AWTEvent.cpp \
../src/jdk/windows/native/sun/windows/awt_BitmapUtil.cpp \
../src/jdk/windows/native/sun/windows/awt_Brush.cpp \
../src/jdk/windows/native/sun/windows/awt_Button.cpp \
../src/jdk/windows/native/sun/windows/awt_Canvas.cpp \
../src/jdk/windows/native/sun/windows/awt_Checkbox.cpp \
../src/jdk/windows/native/sun/windows/awt_Choice.cpp \
../src/jdk/windows/native/sun/windows/awt_Clipboard.cpp \
../src/jdk/windows/native/sun/windows/awt_Color.cpp \
../src/jdk/windows/native/sun/windows/awt_Component.cpp \
../src/jdk/windows/native/sun/windows/awt_Container.cpp \
../src/jdk/windows/native/sun/windows/awt_Cursor.cpp \
../src/jdk/windows/native/sun/windows/awt_DCHolder.cpp \
../src/jdk/windows/native/sun/windows/awt_DataTransferer.cpp \
../src/jdk/windows/native/sun/windows/awt_Debug.cpp \
../src/jdk/windows/native/sun/windows/awt_Desktop.cpp \
../src/jdk/windows/native/sun/windows/awt_DesktopProperties.cpp \
../src/jdk/windows/native/sun/windows/awt_Dialog.cpp \
../src/jdk/windows/native/sun/windows/awt_Dimension.cpp \
../src/jdk/windows/native/sun/windows/awt_DnDDS.cpp \
../src/jdk/windows/native/sun/windows/awt_DnDDT.cpp \
../src/jdk/windows/native/sun/windows/awt_DrawingSurface.cpp \
../src/jdk/windows/native/sun/windows/awt_Event.cpp \
../src/jdk/windows/native/sun/windows/awt_FileDialog.cpp \
../src/jdk/windows/native/sun/windows/awt_Font.cpp \
../src/jdk/windows/native/sun/windows/awt_Frame.cpp \
../src/jdk/windows/native/sun/windows/awt_GDIObject.cpp \
../src/jdk/windows/native/sun/windows/awt_IconCursor.cpp \
../src/jdk/windows/native/sun/windows/awt_InputEvent.cpp \
../src/jdk/windows/native/sun/windows/awt_InputMethod.cpp \
../src/jdk/windows/native/sun/windows/awt_InputTextInfor.cpp \
../src/jdk/windows/native/sun/windows/awt_Insets.cpp \
../src/jdk/windows/native/sun/windows/awt_KeyEvent.cpp \
../src/jdk/windows/native/sun/windows/awt_KeyboardFocusManager.cpp \
../src/jdk/windows/native/sun/windows/awt_Label.cpp \
../src/jdk/windows/native/sun/windows/awt_List.cpp \
../src/jdk/windows/native/sun/windows/awt_Menu.cpp \
../src/jdk/windows/native/sun/windows/awt_MenuBar.cpp \
../src/jdk/windows/native/sun/windows/awt_MenuItem.cpp \
../src/jdk/windows/native/sun/windows/awt_Mlib.cpp \
../src/jdk/windows/native/sun/windows/awt_MouseEvent.cpp \
../src/jdk/windows/native/sun/windows/awt_Object.cpp \
../src/jdk/windows/native/sun/windows/awt_Palette.cpp \
../src/jdk/windows/native/sun/windows/awt_Panel.cpp \
../src/jdk/windows/native/sun/windows/awt_Pen.cpp \
../src/jdk/windows/native/sun/windows/awt_PopupMenu.cpp \
../src/jdk/windows/native/sun/windows/awt_PrintControl.cpp \
../src/jdk/windows/native/sun/windows/awt_PrintDialog.cpp \
../src/jdk/windows/native/sun/windows/awt_PrintJob.cpp \
../src/jdk/windows/native/sun/windows/awt_Rectangle.cpp \
../src/jdk/windows/native/sun/windows/awt_Robot.cpp \
../src/jdk/windows/native/sun/windows/awt_ScrollPane.cpp \
../src/jdk/windows/native/sun/windows/awt_Scrollbar.cpp \
../src/jdk/windows/native/sun/windows/awt_TextArea.cpp \
../src/jdk/windows/native/sun/windows/awt_TextComponent.cpp \
../src/jdk/windows/native/sun/windows/awt_TextField.cpp \
../src/jdk/windows/native/sun/windows/awt_Toolkit.cpp \
../src/jdk/windows/native/sun/windows/awt_TrayIcon.cpp \
../src/jdk/windows/native/sun/windows/awt_Win32GraphicsConfig.cpp \
../src/jdk/windows/native/sun/windows/awt_Win32GraphicsDevice.cpp \
../src/jdk/windows/native/sun/windows/awt_Win32GraphicsEnv.cpp \
../src/jdk/windows/native/sun/windows/awt_Window.cpp \
../src/jdk/windows/native/sun/windows/awt_new.cpp \
../src/jdk/windows/native/sun/windows/awt_ole.cpp \
../src/jdk/windows/native/sun/windows/initIDs.cpp \
../src/jdk/windows/native/sun/windows/jawt.cpp 

OBJS += \
./src/jdk/windows/native/sun/windows/CmdIDList.o \
./src/jdk/windows/native/sun/windows/ComCtl32Util.o \
./src/jdk/windows/native/sun/windows/Devices.o \
./src/jdk/windows/native/sun/windows/DllUtil.o \
./src/jdk/windows/native/sun/windows/GDIHashtable.o \
./src/jdk/windows/native/sun/windows/Hashtable.o \
./src/jdk/windows/native/sun/windows/MouseInfo.o \
./src/jdk/windows/native/sun/windows/ObjectList.o \
./src/jdk/windows/native/sun/windows/ShellFolder2.o \
./src/jdk/windows/native/sun/windows/ThemeReader.o \
./src/jdk/windows/native/sun/windows/WBufferStrategy.o \
./src/jdk/windows/native/sun/windows/WPrinterJob.o \
./src/jdk/windows/native/sun/windows/awt_AWTEvent.o \
./src/jdk/windows/native/sun/windows/awt_BitmapUtil.o \
./src/jdk/windows/native/sun/windows/awt_Brush.o \
./src/jdk/windows/native/sun/windows/awt_Button.o \
./src/jdk/windows/native/sun/windows/awt_Canvas.o \
./src/jdk/windows/native/sun/windows/awt_Checkbox.o \
./src/jdk/windows/native/sun/windows/awt_Choice.o \
./src/jdk/windows/native/sun/windows/awt_Clipboard.o \
./src/jdk/windows/native/sun/windows/awt_Color.o \
./src/jdk/windows/native/sun/windows/awt_Component.o \
./src/jdk/windows/native/sun/windows/awt_Container.o \
./src/jdk/windows/native/sun/windows/awt_Cursor.o \
./src/jdk/windows/native/sun/windows/awt_DCHolder.o \
./src/jdk/windows/native/sun/windows/awt_DataTransferer.o \
./src/jdk/windows/native/sun/windows/awt_Debug.o \
./src/jdk/windows/native/sun/windows/awt_Desktop.o \
./src/jdk/windows/native/sun/windows/awt_DesktopProperties.o \
./src/jdk/windows/native/sun/windows/awt_Dialog.o \
./src/jdk/windows/native/sun/windows/awt_Dimension.o \
./src/jdk/windows/native/sun/windows/awt_DnDDS.o \
./src/jdk/windows/native/sun/windows/awt_DnDDT.o \
./src/jdk/windows/native/sun/windows/awt_DrawingSurface.o \
./src/jdk/windows/native/sun/windows/awt_Event.o \
./src/jdk/windows/native/sun/windows/awt_FileDialog.o \
./src/jdk/windows/native/sun/windows/awt_Font.o \
./src/jdk/windows/native/sun/windows/awt_Frame.o \
./src/jdk/windows/native/sun/windows/awt_GDIObject.o \
./src/jdk/windows/native/sun/windows/awt_IconCursor.o \
./src/jdk/windows/native/sun/windows/awt_InputEvent.o \
./src/jdk/windows/native/sun/windows/awt_InputMethod.o \
./src/jdk/windows/native/sun/windows/awt_InputTextInfor.o \
./src/jdk/windows/native/sun/windows/awt_Insets.o \
./src/jdk/windows/native/sun/windows/awt_KeyEvent.o \
./src/jdk/windows/native/sun/windows/awt_KeyboardFocusManager.o \
./src/jdk/windows/native/sun/windows/awt_Label.o \
./src/jdk/windows/native/sun/windows/awt_List.o \
./src/jdk/windows/native/sun/windows/awt_Menu.o \
./src/jdk/windows/native/sun/windows/awt_MenuBar.o \
./src/jdk/windows/native/sun/windows/awt_MenuItem.o \
./src/jdk/windows/native/sun/windows/awt_Mlib.o \
./src/jdk/windows/native/sun/windows/awt_MouseEvent.o \
./src/jdk/windows/native/sun/windows/awt_Object.o \
./src/jdk/windows/native/sun/windows/awt_Palette.o \
./src/jdk/windows/native/sun/windows/awt_Panel.o \
./src/jdk/windows/native/sun/windows/awt_Pen.o \
./src/jdk/windows/native/sun/windows/awt_PopupMenu.o \
./src/jdk/windows/native/sun/windows/awt_PrintControl.o \
./src/jdk/windows/native/sun/windows/awt_PrintDialog.o \
./src/jdk/windows/native/sun/windows/awt_PrintJob.o \
./src/jdk/windows/native/sun/windows/awt_Rectangle.o \
./src/jdk/windows/native/sun/windows/awt_Robot.o \
./src/jdk/windows/native/sun/windows/awt_ScrollPane.o \
./src/jdk/windows/native/sun/windows/awt_Scrollbar.o \
./src/jdk/windows/native/sun/windows/awt_TextArea.o \
./src/jdk/windows/native/sun/windows/awt_TextComponent.o \
./src/jdk/windows/native/sun/windows/awt_TextField.o \
./src/jdk/windows/native/sun/windows/awt_Toolkit.o \
./src/jdk/windows/native/sun/windows/awt_TrayIcon.o \
./src/jdk/windows/native/sun/windows/awt_Win32GraphicsConfig.o \
./src/jdk/windows/native/sun/windows/awt_Win32GraphicsDevice.o \
./src/jdk/windows/native/sun/windows/awt_Win32GraphicsEnv.o \
./src/jdk/windows/native/sun/windows/awt_Window.o \
./src/jdk/windows/native/sun/windows/awt_new.o \
./src/jdk/windows/native/sun/windows/awt_ole.o \
./src/jdk/windows/native/sun/windows/initIDs.o \
./src/jdk/windows/native/sun/windows/jawt.o 

CPP_DEPS += \
./src/jdk/windows/native/sun/windows/CmdIDList.d \
./src/jdk/windows/native/sun/windows/ComCtl32Util.d \
./src/jdk/windows/native/sun/windows/Devices.d \
./src/jdk/windows/native/sun/windows/DllUtil.d \
./src/jdk/windows/native/sun/windows/GDIHashtable.d \
./src/jdk/windows/native/sun/windows/Hashtable.d \
./src/jdk/windows/native/sun/windows/MouseInfo.d \
./src/jdk/windows/native/sun/windows/ObjectList.d \
./src/jdk/windows/native/sun/windows/ShellFolder2.d \
./src/jdk/windows/native/sun/windows/ThemeReader.d \
./src/jdk/windows/native/sun/windows/WBufferStrategy.d \
./src/jdk/windows/native/sun/windows/WPrinterJob.d \
./src/jdk/windows/native/sun/windows/awt_AWTEvent.d \
./src/jdk/windows/native/sun/windows/awt_BitmapUtil.d \
./src/jdk/windows/native/sun/windows/awt_Brush.d \
./src/jdk/windows/native/sun/windows/awt_Button.d \
./src/jdk/windows/native/sun/windows/awt_Canvas.d \
./src/jdk/windows/native/sun/windows/awt_Checkbox.d \
./src/jdk/windows/native/sun/windows/awt_Choice.d \
./src/jdk/windows/native/sun/windows/awt_Clipboard.d \
./src/jdk/windows/native/sun/windows/awt_Color.d \
./src/jdk/windows/native/sun/windows/awt_Component.d \
./src/jdk/windows/native/sun/windows/awt_Container.d \
./src/jdk/windows/native/sun/windows/awt_Cursor.d \
./src/jdk/windows/native/sun/windows/awt_DCHolder.d \
./src/jdk/windows/native/sun/windows/awt_DataTransferer.d \
./src/jdk/windows/native/sun/windows/awt_Debug.d \
./src/jdk/windows/native/sun/windows/awt_Desktop.d \
./src/jdk/windows/native/sun/windows/awt_DesktopProperties.d \
./src/jdk/windows/native/sun/windows/awt_Dialog.d \
./src/jdk/windows/native/sun/windows/awt_Dimension.d \
./src/jdk/windows/native/sun/windows/awt_DnDDS.d \
./src/jdk/windows/native/sun/windows/awt_DnDDT.d \
./src/jdk/windows/native/sun/windows/awt_DrawingSurface.d \
./src/jdk/windows/native/sun/windows/awt_Event.d \
./src/jdk/windows/native/sun/windows/awt_FileDialog.d \
./src/jdk/windows/native/sun/windows/awt_Font.d \
./src/jdk/windows/native/sun/windows/awt_Frame.d \
./src/jdk/windows/native/sun/windows/awt_GDIObject.d \
./src/jdk/windows/native/sun/windows/awt_IconCursor.d \
./src/jdk/windows/native/sun/windows/awt_InputEvent.d \
./src/jdk/windows/native/sun/windows/awt_InputMethod.d \
./src/jdk/windows/native/sun/windows/awt_InputTextInfor.d \
./src/jdk/windows/native/sun/windows/awt_Insets.d \
./src/jdk/windows/native/sun/windows/awt_KeyEvent.d \
./src/jdk/windows/native/sun/windows/awt_KeyboardFocusManager.d \
./src/jdk/windows/native/sun/windows/awt_Label.d \
./src/jdk/windows/native/sun/windows/awt_List.d \
./src/jdk/windows/native/sun/windows/awt_Menu.d \
./src/jdk/windows/native/sun/windows/awt_MenuBar.d \
./src/jdk/windows/native/sun/windows/awt_MenuItem.d \
./src/jdk/windows/native/sun/windows/awt_Mlib.d \
./src/jdk/windows/native/sun/windows/awt_MouseEvent.d \
./src/jdk/windows/native/sun/windows/awt_Object.d \
./src/jdk/windows/native/sun/windows/awt_Palette.d \
./src/jdk/windows/native/sun/windows/awt_Panel.d \
./src/jdk/windows/native/sun/windows/awt_Pen.d \
./src/jdk/windows/native/sun/windows/awt_PopupMenu.d \
./src/jdk/windows/native/sun/windows/awt_PrintControl.d \
./src/jdk/windows/native/sun/windows/awt_PrintDialog.d \
./src/jdk/windows/native/sun/windows/awt_PrintJob.d \
./src/jdk/windows/native/sun/windows/awt_Rectangle.d \
./src/jdk/windows/native/sun/windows/awt_Robot.d \
./src/jdk/windows/native/sun/windows/awt_ScrollPane.d \
./src/jdk/windows/native/sun/windows/awt_Scrollbar.d \
./src/jdk/windows/native/sun/windows/awt_TextArea.d \
./src/jdk/windows/native/sun/windows/awt_TextComponent.d \
./src/jdk/windows/native/sun/windows/awt_TextField.d \
./src/jdk/windows/native/sun/windows/awt_Toolkit.d \
./src/jdk/windows/native/sun/windows/awt_TrayIcon.d \
./src/jdk/windows/native/sun/windows/awt_Win32GraphicsConfig.d \
./src/jdk/windows/native/sun/windows/awt_Win32GraphicsDevice.d \
./src/jdk/windows/native/sun/windows/awt_Win32GraphicsEnv.d \
./src/jdk/windows/native/sun/windows/awt_Window.d \
./src/jdk/windows/native/sun/windows/awt_new.d \
./src/jdk/windows/native/sun/windows/awt_ole.d \
./src/jdk/windows/native/sun/windows/initIDs.d \
./src/jdk/windows/native/sun/windows/jawt.d 


# Each subdirectory must supply rules for building sources it contributes
src/jdk/windows/native/sun/windows/%.o: ../src/jdk/windows/native/sun/windows/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


