################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/jdk/share/native/sun/font/layout/AlternateSubstSubtables.cpp \
../src/jdk/share/native/sun/font/layout/AnchorTables.cpp \
../src/jdk/share/native/sun/font/layout/ArabicLayoutEngine.cpp \
../src/jdk/share/native/sun/font/layout/ArabicShaping.cpp \
../src/jdk/share/native/sun/font/layout/CanonData.cpp \
../src/jdk/share/native/sun/font/layout/CanonShaping.cpp \
../src/jdk/share/native/sun/font/layout/ClassDefinitionTables.cpp \
../src/jdk/share/native/sun/font/layout/ContextualGlyphSubstProc.cpp \
../src/jdk/share/native/sun/font/layout/ContextualSubstSubtables.cpp \
../src/jdk/share/native/sun/font/layout/CoverageTables.cpp \
../src/jdk/share/native/sun/font/layout/CursiveAttachmentSubtables.cpp \
../src/jdk/share/native/sun/font/layout/DeviceTables.cpp \
../src/jdk/share/native/sun/font/layout/ExtensionSubtables.cpp \
../src/jdk/share/native/sun/font/layout/Features.cpp \
../src/jdk/share/native/sun/font/layout/GDEFMarkFilter.cpp \
../src/jdk/share/native/sun/font/layout/GXLayoutEngine.cpp \
../src/jdk/share/native/sun/font/layout/GlyphDefinitionTables.cpp \
../src/jdk/share/native/sun/font/layout/GlyphIterator.cpp \
../src/jdk/share/native/sun/font/layout/GlyphLookupTables.cpp \
../src/jdk/share/native/sun/font/layout/GlyphPositionAdjustments.cpp \
../src/jdk/share/native/sun/font/layout/GlyphPositioningTables.cpp \
../src/jdk/share/native/sun/font/layout/GlyphPosnLookupProc.cpp \
../src/jdk/share/native/sun/font/layout/GlyphSubstLookupProc.cpp \
../src/jdk/share/native/sun/font/layout/GlyphSubstitutionTables.cpp \
../src/jdk/share/native/sun/font/layout/HanLayoutEngine.cpp \
../src/jdk/share/native/sun/font/layout/HangulLayoutEngine.cpp \
../src/jdk/share/native/sun/font/layout/IndicClassTables.cpp \
../src/jdk/share/native/sun/font/layout/IndicLayoutEngine.cpp \
../src/jdk/share/native/sun/font/layout/IndicRearrangementProcessor.cpp \
../src/jdk/share/native/sun/font/layout/IndicReordering.cpp \
../src/jdk/share/native/sun/font/layout/KernTable.cpp \
../src/jdk/share/native/sun/font/layout/KhmerLayoutEngine.cpp \
../src/jdk/share/native/sun/font/layout/KhmerReordering.cpp \
../src/jdk/share/native/sun/font/layout/LEFontInstance.cpp \
../src/jdk/share/native/sun/font/layout/LEGlyphStorage.cpp \
../src/jdk/share/native/sun/font/layout/LEInsertionList.cpp \
../src/jdk/share/native/sun/font/layout/LayoutEngine.cpp \
../src/jdk/share/native/sun/font/layout/LigatureSubstProc.cpp \
../src/jdk/share/native/sun/font/layout/LigatureSubstSubtables.cpp \
../src/jdk/share/native/sun/font/layout/LookupProcessor.cpp \
../src/jdk/share/native/sun/font/layout/LookupTables.cpp \
../src/jdk/share/native/sun/font/layout/Lookups.cpp \
../src/jdk/share/native/sun/font/layout/MPreFixups.cpp \
../src/jdk/share/native/sun/font/layout/MarkArrays.cpp \
../src/jdk/share/native/sun/font/layout/MarkToBasePosnSubtables.cpp \
../src/jdk/share/native/sun/font/layout/MarkToLigaturePosnSubtables.cpp \
../src/jdk/share/native/sun/font/layout/MarkToMarkPosnSubtables.cpp \
../src/jdk/share/native/sun/font/layout/MirroredCharData.cpp \
../src/jdk/share/native/sun/font/layout/MorphTables.cpp \
../src/jdk/share/native/sun/font/layout/MultipleSubstSubtables.cpp \
../src/jdk/share/native/sun/font/layout/NonContextualGlyphSubstProc.cpp \
../src/jdk/share/native/sun/font/layout/OpenTypeLayoutEngine.cpp \
../src/jdk/share/native/sun/font/layout/OpenTypeUtilities.cpp \
../src/jdk/share/native/sun/font/layout/PairPositioningSubtables.cpp \
../src/jdk/share/native/sun/font/layout/ScriptAndLanguage.cpp \
../src/jdk/share/native/sun/font/layout/ScriptAndLanguageTags.cpp \
../src/jdk/share/native/sun/font/layout/SegmentArrayProcessor.cpp \
../src/jdk/share/native/sun/font/layout/SegmentSingleProcessor.cpp \
../src/jdk/share/native/sun/font/layout/ShapingTypeData.cpp \
../src/jdk/share/native/sun/font/layout/SimpleArrayProcessor.cpp \
../src/jdk/share/native/sun/font/layout/SinglePositioningSubtables.cpp \
../src/jdk/share/native/sun/font/layout/SingleSubstitutionSubtables.cpp \
../src/jdk/share/native/sun/font/layout/SingleTableProcessor.cpp \
../src/jdk/share/native/sun/font/layout/StateTableProcessor.cpp \
../src/jdk/share/native/sun/font/layout/SubstitutionLookups.cpp \
../src/jdk/share/native/sun/font/layout/SubtableProcessor.cpp \
../src/jdk/share/native/sun/font/layout/SunLayoutEngine.cpp \
../src/jdk/share/native/sun/font/layout/ThaiLayoutEngine.cpp \
../src/jdk/share/native/sun/font/layout/ThaiShaping.cpp \
../src/jdk/share/native/sun/font/layout/ThaiStateTables.cpp \
../src/jdk/share/native/sun/font/layout/TibetanLayoutEngine.cpp \
../src/jdk/share/native/sun/font/layout/TibetanReordering.cpp \
../src/jdk/share/native/sun/font/layout/TrimmedArrayProcessor.cpp \
../src/jdk/share/native/sun/font/layout/ValueRecords.cpp 

OBJS += \
./src/jdk/share/native/sun/font/layout/AlternateSubstSubtables.o \
./src/jdk/share/native/sun/font/layout/AnchorTables.o \
./src/jdk/share/native/sun/font/layout/ArabicLayoutEngine.o \
./src/jdk/share/native/sun/font/layout/ArabicShaping.o \
./src/jdk/share/native/sun/font/layout/CanonData.o \
./src/jdk/share/native/sun/font/layout/CanonShaping.o \
./src/jdk/share/native/sun/font/layout/ClassDefinitionTables.o \
./src/jdk/share/native/sun/font/layout/ContextualGlyphSubstProc.o \
./src/jdk/share/native/sun/font/layout/ContextualSubstSubtables.o \
./src/jdk/share/native/sun/font/layout/CoverageTables.o \
./src/jdk/share/native/sun/font/layout/CursiveAttachmentSubtables.o \
./src/jdk/share/native/sun/font/layout/DeviceTables.o \
./src/jdk/share/native/sun/font/layout/ExtensionSubtables.o \
./src/jdk/share/native/sun/font/layout/Features.o \
./src/jdk/share/native/sun/font/layout/GDEFMarkFilter.o \
./src/jdk/share/native/sun/font/layout/GXLayoutEngine.o \
./src/jdk/share/native/sun/font/layout/GlyphDefinitionTables.o \
./src/jdk/share/native/sun/font/layout/GlyphIterator.o \
./src/jdk/share/native/sun/font/layout/GlyphLookupTables.o \
./src/jdk/share/native/sun/font/layout/GlyphPositionAdjustments.o \
./src/jdk/share/native/sun/font/layout/GlyphPositioningTables.o \
./src/jdk/share/native/sun/font/layout/GlyphPosnLookupProc.o \
./src/jdk/share/native/sun/font/layout/GlyphSubstLookupProc.o \
./src/jdk/share/native/sun/font/layout/GlyphSubstitutionTables.o \
./src/jdk/share/native/sun/font/layout/HanLayoutEngine.o \
./src/jdk/share/native/sun/font/layout/HangulLayoutEngine.o \
./src/jdk/share/native/sun/font/layout/IndicClassTables.o \
./src/jdk/share/native/sun/font/layout/IndicLayoutEngine.o \
./src/jdk/share/native/sun/font/layout/IndicRearrangementProcessor.o \
./src/jdk/share/native/sun/font/layout/IndicReordering.o \
./src/jdk/share/native/sun/font/layout/KernTable.o \
./src/jdk/share/native/sun/font/layout/KhmerLayoutEngine.o \
./src/jdk/share/native/sun/font/layout/KhmerReordering.o \
./src/jdk/share/native/sun/font/layout/LEFontInstance.o \
./src/jdk/share/native/sun/font/layout/LEGlyphStorage.o \
./src/jdk/share/native/sun/font/layout/LEInsertionList.o \
./src/jdk/share/native/sun/font/layout/LayoutEngine.o \
./src/jdk/share/native/sun/font/layout/LigatureSubstProc.o \
./src/jdk/share/native/sun/font/layout/LigatureSubstSubtables.o \
./src/jdk/share/native/sun/font/layout/LookupProcessor.o \
./src/jdk/share/native/sun/font/layout/LookupTables.o \
./src/jdk/share/native/sun/font/layout/Lookups.o \
./src/jdk/share/native/sun/font/layout/MPreFixups.o \
./src/jdk/share/native/sun/font/layout/MarkArrays.o \
./src/jdk/share/native/sun/font/layout/MarkToBasePosnSubtables.o \
./src/jdk/share/native/sun/font/layout/MarkToLigaturePosnSubtables.o \
./src/jdk/share/native/sun/font/layout/MarkToMarkPosnSubtables.o \
./src/jdk/share/native/sun/font/layout/MirroredCharData.o \
./src/jdk/share/native/sun/font/layout/MorphTables.o \
./src/jdk/share/native/sun/font/layout/MultipleSubstSubtables.o \
./src/jdk/share/native/sun/font/layout/NonContextualGlyphSubstProc.o \
./src/jdk/share/native/sun/font/layout/OpenTypeLayoutEngine.o \
./src/jdk/share/native/sun/font/layout/OpenTypeUtilities.o \
./src/jdk/share/native/sun/font/layout/PairPositioningSubtables.o \
./src/jdk/share/native/sun/font/layout/ScriptAndLanguage.o \
./src/jdk/share/native/sun/font/layout/ScriptAndLanguageTags.o \
./src/jdk/share/native/sun/font/layout/SegmentArrayProcessor.o \
./src/jdk/share/native/sun/font/layout/SegmentSingleProcessor.o \
./src/jdk/share/native/sun/font/layout/ShapingTypeData.o \
./src/jdk/share/native/sun/font/layout/SimpleArrayProcessor.o \
./src/jdk/share/native/sun/font/layout/SinglePositioningSubtables.o \
./src/jdk/share/native/sun/font/layout/SingleSubstitutionSubtables.o \
./src/jdk/share/native/sun/font/layout/SingleTableProcessor.o \
./src/jdk/share/native/sun/font/layout/StateTableProcessor.o \
./src/jdk/share/native/sun/font/layout/SubstitutionLookups.o \
./src/jdk/share/native/sun/font/layout/SubtableProcessor.o \
./src/jdk/share/native/sun/font/layout/SunLayoutEngine.o \
./src/jdk/share/native/sun/font/layout/ThaiLayoutEngine.o \
./src/jdk/share/native/sun/font/layout/ThaiShaping.o \
./src/jdk/share/native/sun/font/layout/ThaiStateTables.o \
./src/jdk/share/native/sun/font/layout/TibetanLayoutEngine.o \
./src/jdk/share/native/sun/font/layout/TibetanReordering.o \
./src/jdk/share/native/sun/font/layout/TrimmedArrayProcessor.o \
./src/jdk/share/native/sun/font/layout/ValueRecords.o 

CPP_DEPS += \
./src/jdk/share/native/sun/font/layout/AlternateSubstSubtables.d \
./src/jdk/share/native/sun/font/layout/AnchorTables.d \
./src/jdk/share/native/sun/font/layout/ArabicLayoutEngine.d \
./src/jdk/share/native/sun/font/layout/ArabicShaping.d \
./src/jdk/share/native/sun/font/layout/CanonData.d \
./src/jdk/share/native/sun/font/layout/CanonShaping.d \
./src/jdk/share/native/sun/font/layout/ClassDefinitionTables.d \
./src/jdk/share/native/sun/font/layout/ContextualGlyphSubstProc.d \
./src/jdk/share/native/sun/font/layout/ContextualSubstSubtables.d \
./src/jdk/share/native/sun/font/layout/CoverageTables.d \
./src/jdk/share/native/sun/font/layout/CursiveAttachmentSubtables.d \
./src/jdk/share/native/sun/font/layout/DeviceTables.d \
./src/jdk/share/native/sun/font/layout/ExtensionSubtables.d \
./src/jdk/share/native/sun/font/layout/Features.d \
./src/jdk/share/native/sun/font/layout/GDEFMarkFilter.d \
./src/jdk/share/native/sun/font/layout/GXLayoutEngine.d \
./src/jdk/share/native/sun/font/layout/GlyphDefinitionTables.d \
./src/jdk/share/native/sun/font/layout/GlyphIterator.d \
./src/jdk/share/native/sun/font/layout/GlyphLookupTables.d \
./src/jdk/share/native/sun/font/layout/GlyphPositionAdjustments.d \
./src/jdk/share/native/sun/font/layout/GlyphPositioningTables.d \
./src/jdk/share/native/sun/font/layout/GlyphPosnLookupProc.d \
./src/jdk/share/native/sun/font/layout/GlyphSubstLookupProc.d \
./src/jdk/share/native/sun/font/layout/GlyphSubstitutionTables.d \
./src/jdk/share/native/sun/font/layout/HanLayoutEngine.d \
./src/jdk/share/native/sun/font/layout/HangulLayoutEngine.d \
./src/jdk/share/native/sun/font/layout/IndicClassTables.d \
./src/jdk/share/native/sun/font/layout/IndicLayoutEngine.d \
./src/jdk/share/native/sun/font/layout/IndicRearrangementProcessor.d \
./src/jdk/share/native/sun/font/layout/IndicReordering.d \
./src/jdk/share/native/sun/font/layout/KernTable.d \
./src/jdk/share/native/sun/font/layout/KhmerLayoutEngine.d \
./src/jdk/share/native/sun/font/layout/KhmerReordering.d \
./src/jdk/share/native/sun/font/layout/LEFontInstance.d \
./src/jdk/share/native/sun/font/layout/LEGlyphStorage.d \
./src/jdk/share/native/sun/font/layout/LEInsertionList.d \
./src/jdk/share/native/sun/font/layout/LayoutEngine.d \
./src/jdk/share/native/sun/font/layout/LigatureSubstProc.d \
./src/jdk/share/native/sun/font/layout/LigatureSubstSubtables.d \
./src/jdk/share/native/sun/font/layout/LookupProcessor.d \
./src/jdk/share/native/sun/font/layout/LookupTables.d \
./src/jdk/share/native/sun/font/layout/Lookups.d \
./src/jdk/share/native/sun/font/layout/MPreFixups.d \
./src/jdk/share/native/sun/font/layout/MarkArrays.d \
./src/jdk/share/native/sun/font/layout/MarkToBasePosnSubtables.d \
./src/jdk/share/native/sun/font/layout/MarkToLigaturePosnSubtables.d \
./src/jdk/share/native/sun/font/layout/MarkToMarkPosnSubtables.d \
./src/jdk/share/native/sun/font/layout/MirroredCharData.d \
./src/jdk/share/native/sun/font/layout/MorphTables.d \
./src/jdk/share/native/sun/font/layout/MultipleSubstSubtables.d \
./src/jdk/share/native/sun/font/layout/NonContextualGlyphSubstProc.d \
./src/jdk/share/native/sun/font/layout/OpenTypeLayoutEngine.d \
./src/jdk/share/native/sun/font/layout/OpenTypeUtilities.d \
./src/jdk/share/native/sun/font/layout/PairPositioningSubtables.d \
./src/jdk/share/native/sun/font/layout/ScriptAndLanguage.d \
./src/jdk/share/native/sun/font/layout/ScriptAndLanguageTags.d \
./src/jdk/share/native/sun/font/layout/SegmentArrayProcessor.d \
./src/jdk/share/native/sun/font/layout/SegmentSingleProcessor.d \
./src/jdk/share/native/sun/font/layout/ShapingTypeData.d \
./src/jdk/share/native/sun/font/layout/SimpleArrayProcessor.d \
./src/jdk/share/native/sun/font/layout/SinglePositioningSubtables.d \
./src/jdk/share/native/sun/font/layout/SingleSubstitutionSubtables.d \
./src/jdk/share/native/sun/font/layout/SingleTableProcessor.d \
./src/jdk/share/native/sun/font/layout/StateTableProcessor.d \
./src/jdk/share/native/sun/font/layout/SubstitutionLookups.d \
./src/jdk/share/native/sun/font/layout/SubtableProcessor.d \
./src/jdk/share/native/sun/font/layout/SunLayoutEngine.d \
./src/jdk/share/native/sun/font/layout/ThaiLayoutEngine.d \
./src/jdk/share/native/sun/font/layout/ThaiShaping.d \
./src/jdk/share/native/sun/font/layout/ThaiStateTables.d \
./src/jdk/share/native/sun/font/layout/TibetanLayoutEngine.d \
./src/jdk/share/native/sun/font/layout/TibetanReordering.d \
./src/jdk/share/native/sun/font/layout/TrimmedArrayProcessor.d \
./src/jdk/share/native/sun/font/layout/ValueRecords.d 


# Each subdirectory must supply rules for building sources it contributes
src/jdk/share/native/sun/font/layout/%.o: ../src/jdk/share/native/sun/font/layout/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


